### ISSUE TITLE
shared library `zlib.so` missing in v1.2.12

### ISSUE THREAD

**Issue by njzjz** [AnacondaRecipes/zlib-feedstock#10]
Built by #9 - https://repo.anaconda.com/pkgs/main/linux-64/zlib-1.2.12-h7f8727e_0.tar.bz2

Please remove this package at once as it will break other packages.

**Comment by jehturner** [comment]
This has broken `import matplotlib` for us on CentOS 7 (which is the minimum OS requirement documented [here](https://docs.anaconda.com/anaconda/install/)). Matplotlib still runs on CentOS 8 because the linker falls back to `/lib64/libz.so` instead, which is new enough on that OS to contain the required symbols, but it should be using the env's own `libz.so`, as per the `libpng` conda package dependency. Yesterday's `zlib` build only contains a static library... Thanks.
